### PR TITLE
Added React support

### PR DESCRIPTION
**Pull request by JanneHarju**
Added react support to TypeScriptReact (tsx), javascript (js) and
javascriptReact (jsx) -files.
jsx file is not tested.

### CODE REVIEW

**Comment by Zignd** [comment]
Can you recreate your pull request? The last commit on the master branch was a "work in progress" that I shouldn't have pushed. I removed the commit but it invalidates your pull request. Sorry for the inconvenience.

**Comment by Zignd** [comment]
I've just finished the tests with the code you changed. It works flawlessly. As soon as you recreate the pull request I'll publish a new version of the extension. :)

**Comment by JanneHarju** [comment]
Is this ok now or should I make new fork or something?

**Comment by Zignd** [comment]
Actually, I think it would be easier if you simply forked the project again, copied the change into this new fork, and created a new pull request.

**Comment by JanneHarju** [comment]
hmm. github says that I have already forked it so I don't now how I can fork it again. I think this must be closed first.

**Comment by JanneHarju** [comment]
hmm so did you have some changes or why all this?

**Comment by JanneHarju** [comment]
I think that if I merge your changes to my fork?

**Comment by Zignd** [comment]
> hmm. github says that I have already forked it so I don't now how I can fork it again. I think this must be closed first.

Do the following. Save your changes somewhere, that one you did on the `extension.ts`. Delete the forked repository. And fork it again. I should work like that.

> hmm so did you have some changes or why all this?

I was implementing a [Language Server](https://code.visualstudio.com/docs/extensions/example-language-server), but I ended up doing that on the master branch, it's wrong I know xD. The last commit had changes related to that but I have not finished it yet, so it would break the extension. For that reason I removed the last commit that had those breaking changes related to the language server, returning the branch to a working state.

**Comment by Zignd** [comment]
> I think that if I merge your changes to my fork?

Better not do that, the change was a git reset on the last commit, you would have to deal with lots of complicated things unnecessarily.

**Pull request closed without merging**
