### PR TITLE
User defined languages

### PR DESCRIPTION
**Pull request by natecorkish**
This pull request gives the end user the choice to choose their own languages to show css completions. For example, say someone wants to add autocompletions to a file called `.johndoe` they can add it to their settings like so:

```
    "html-css-class-completion.enabledHTMLLanguages": [
        "html",
        "django-html",
        "razor",
        "php",
        "blade",
        "vue",
        "twig",
        "markdown",
        "erb",
        "handlebars",
        "ejs",
        "svelte",
       "johndoe"
    ],
```

This will save time for all the individual edge cases we have with people wanting support for different file types.

### CODE REVIEW

**Comment by vikbert** [comment]
nice feature. it will be nice to get this PR merged as soon as possible. thx.

**Comment by a6h-s** [comment]
@zignd bump

**Comment by zignd** [comment]
That's an amazing contribution @natecorkish! I'll test it and release it as soon as I can!

By the way, thanks for the mention @a6h-s, I totally missed the initial notification for this PR.

**Comment by zignd** [comment]
@natecorkish I was trying it out locally and it's working perfectly, but I did notice that when the user updates the configurations, the changes are not taking place. I believe it's likely because it's necessary to listen to those changes [here in the code](https://github.com/zignd/HTML-CSS-Class-Completion/blob/869654d900b82babfe41d4979ad801c468b45ea7/src/extension.ts#L140-L157) and then properly update the `context.subscriptions`.

Do you think you could add this detail as well? Otherwise I can still do it on my side once I merge it, no problem at all. Also, thanks for taking your time to implement it :)

**Comment by zignd** [comment]
Merged to master manually https://github.com/zignd/HTML-CSS-Class-Completion/commit/524b4f02d8ccd7fad48c2f7bafe9fc38db451c80

**Comment by vikbert** [comment]
nice work. keep going. thx

**Pull request closed without merging**
