### PR TITLE
Tailwind css support

### PR DESCRIPTION
**Pull request by m2de**
I was hoping we could merge in support for [Tailwind CSS](https://tailwindcss.com) which has some unique ways of applying styles and I think this would be a really useful addition. Tailwind is a new CSS Framework which uses custom CSS tags through PostCss. The `@apply` syntax is used to trigger the intellisense.

### CODE REVIEW

**Comment by zignd** [comment]
Sorry for taking so long to reply, and thanks for the contribution, but I checked the Tailwind documentation, and it seems that you have to use a period before the class name. I tried your change and it is working, but only when you're separating your classes with spaces.

Do you think you could improve it so completion triggers on the period (`.`)? Like so, `@apply .<triggers when the cursor is here>` and so on `@apply .btn .<triggers here>`. I believe you're more versed in this framework than me, then correct me if I'm wrong.

**Comment by m2de** [comment]
Thanks @zignd for your response. The framework supports both syntaxes, `@apply .class` and `@apply class`. I did try simply adding the `.` to the regex but that didn't seem to work. I will have another go at it though.

**Comment by zignd** [comment]
That's good to know, then let me know if you end up finding a solution for that. I'm at work right now, but there's one thing you can try regarding the `.`. VS Code's completion API lets you parameterize the characters that will trigger the completion popup.

The extension currently triggers on quotes, single quotes and space characters, [here's the point in which those values are set](https://github.com/zignd/HTML-CSS-Class-Completion/blob/master/src/extension.ts#L13) and then you can easily find the reference to the variable in the same file.

**Comment by m2de** [comment]
Hi @zignd ... Unfortunately I'm not able to resolve the issue with the `.` trigger. It seems to be specific to the `.` in vscode as I can specify other chars and the trigger works, but not with a dot. I assume because it is such a common trigger for standard language features. As I said though, the syntax without dot is supported by the framework and commonly used because it is easier to copy a set of classes from html into the css when refactoring markup into css components.

**Comment by zignd** [comment]
Ok then, no problem @m2de :) I tested the pull request already, so I will merge it for now and release a new version once I get home. Thanks again!

**Comment by m2de** [comment]
Hey @zignd. Thanks very much ... I have been doing some more experimenting and I think I have worked out a solution so please hold off release, I will try and open another PR for supporting dot syntax when I have fully tested it.

**Comment by zignd** [comment]
Woah that's great! I will wait for your pull request then.

**Pull request merged**
